import type { PlayerClass, ClassDef } from '../stores/types';

export const CLASS_DEFS: Record<PlayerClass, ClassDef> = {
  sentinel: {
    id: 'sentinel',
    name: 'Sentinel',
    role: 'Tank',
    description: 'An unyielding bulwark clad in blessed iron. Draws enemy wrath and endures what would shatter lesser warriors.',
    hp: 180,
    stamina: 50,
    attackRange: 50,
    color: '#c0c0c0',
    meshType: 'heavy_armor',
    abilities: [
      {
        id: 'shield_strike',
        name: 'Shield Strike',
        slot: 'primary',
        cooldownTicks: 44,
        staminaCost: 0,
        range: 50,
        damage: 16,
        projectileSpeed: 0,
        aoeRadius: 0,
        element: 'none',
        visual: 'melee_instant',
      },
      {
        id: 'taunt',
        name: 'Taunt',
        slot: 'q',
        cooldownTicks: 80,
        staminaCost: 15,
        range: 100,
        damage: 0,
        projectileSpeed: 0,
        aoeRadius: 100,
        element: 'none',
        visual: 'self_aoe',
        duration: 60,
        buffEffect: 'taunt',
      },
      {
        id: 'fortress',
        name: 'Fortress',
        slot: 'e',
        cooldownTicks: 100,
        staminaCost: 20,
        range: 0,
        damage: 0,
        projectileSpeed: 0,
        aoeRadius: 0,
        element: 'holy',
        visual: 'self_buff',
        duration: 60,
        buffEffect: 'damage_reduction',
        buffValue: 0.5,
      },
      {
        id: 'consecrate',
        name: 'Consecrate',
        slot: 'r',
        cooldownTicks: 140,
        staminaCost: 25,
        range: 0,
        damage: 15,
        projectileSpeed: 0,
        aoeRadius: 70,
        element: 'holy',
        visual: 'self_aoe',
      },
    ],
  },

  reaver: {
    id: 'reaver',
    name: 'Reaver',
    role: 'Melee DPS',
    description: 'A whirlwind of rage and sharpened steel. Sacrifices caution for devastating cleaving strikes.',
    hp: 110,
    stamina: 65,
    attackRange: 50,
    color: '#ff3333',
    meshType: 'dual_wield',
    abilities: [
      {
        id: 'cleave',
        name: 'Cleave',
        slot: 'primary',
        cooldownTicks: 32,
        staminaCost: 0,
        range: 50,
        damage: 20,
        projectileSpeed: 0,
        aoeRadius: 40,
        element: 'none',
        visual: 'melee_instant',
      },
      {
        id: 'frenzy',
        name: 'Frenzy',
        slot: 'q',
        cooldownTicks: 100,
        staminaCost: 18,
        range: 0,
        damage: 0,
        projectileSpeed: 0,
        aoeRadius: 0,
        element: 'fire',
        visual: 'self_buff',
        duration: 60,
        buffEffect: 'attack_speed',
        buffValue: 0.4,
      },
      {
        id: 'rend',
        name: 'Rend',
        slot: 'e',
        cooldownTicks: 60,
        staminaCost: 15,
        range: 50,
        damage: 30,
        projectileSpeed: 0,
        aoeRadius: 0,
        element: 'none',
        visual: 'melee_instant',
        dotDamage: 4,
        dotDuration: 40,
      },
      {
        id: 'execute',
        name: 'Execute',
        slot: 'r',
        cooldownTicks: 100,
        staminaCost: 20,
        range: 50,
        damage: 45,
        projectileSpeed: 0,
        aoeRadius: 0,
        element: 'none',
        visual: 'melee_instant',
      },
    ],
  },

  shade: {
    id: 'shade',
    name: 'Shade',
    role: 'Melee Assassin',
    description: 'A phantom in the dark, striking from unseen angles. Poisons linger long after the blade withdraws.',
    hp: 85,
    stamina: 90,
    attackRange: 45,
    color: '#4ade80',
    meshType: 'slim_rogue',
    abilities: [
      {
        id: 'backstab',
        name: 'Backstab',
        slot: 'primary',
        cooldownTicks: 28,
        staminaCost: 0,
        range: 45,
        damage: 22,
        projectileSpeed: 0,
        aoeRadius: 0,
        element: 'none',
        visual: 'melee_instant',
      },
      {
        id: 'smoke_bomb',
        name: 'Smoke Bomb',
        slot: 'q',
        cooldownTicks: 120,
        staminaCost: 20,
        range: 0,
        damage: 0,
        projectileSpeed: 0,
        aoeRadius: 80,
        element: 'shadow',
        visual: 'self_aoe',
        duration: 40,
        buffEffect: 'stealth',
      },
      {
        id: 'poison_strike',
        name: 'Poison Strike',
        slot: 'e',
        cooldownTicks: 50,
        staminaCost: 14,
        range: 45,
        damage: 18,
        projectileSpeed: 0,
        aoeRadius: 0,
        element: 'shadow',
        visual: 'melee_instant',
        dotDamage: 5,
        dotDuration: 50,
      },
      {
        id: 'shadow_step',
        name: 'Shadow Step',
        slot: 'r',
        cooldownTicks: 100,
        staminaCost: 18,
        range: 0,
        damage: 0,
        projectileSpeed: 0,
        aoeRadius: 0,
        element: 'shadow',
        visual: 'self_buff',
        duration: 50,
        buffEffect: 'attack_speed',
        buffValue: 0.3,
      },
    ],
  },

  warden: {
    id: 'warden',
    name: 'Warden',
    role: 'Ranged Physical',
    description: 'A dead-eyed archer whose bone-tipped shafts find their mark across the longest halls. Patient. Precise. Lethal.',
    hp: 95,
    stamina: 75,
    attackRange: 220,
    color: '#e8dcc4',
    meshType: 'ranger',
    abilities: [
      {
        id: 'shoot_arrow',
        name: 'Shoot Arrow',
        slot: 'primary',
        cooldownTicks: 36,
        staminaCost: 0,
        range: 220,
        damage: 15,
        projectileSpeed: 8,
        aoeRadius: 0,
        element: 'none',
        visual: 'projectile',
      },
      {
        id: 'volley',
        name: 'Volley',
        slot: 'q',
        cooldownTicks: 100,
        staminaCost: 22,
        range: 200,
        damage: 12,
        projectileSpeed: 0,
        aoeRadius: 60,
        element: 'none',
        visual: 'targeted_aoe',
        duration: 30,
      },
      {
        id: 'piercing_shot',
        name: 'Piercing Shot',
        slot: 'e',
        cooldownTicks: 60,
        staminaCost: 16,
        range: 220,
        damage: 35,
        projectileSpeed: 10,
        aoeRadius: 0,
        element: 'none',
        visual: 'projectile',
        piercing: true,
      },
      {
        id: 'frost_trap',
        name: 'Frost Trap',
        slot: 'r',
        cooldownTicks: 100,
        staminaCost: 18,
        range: 200,
        damage: 20,
        projectileSpeed: 0,
        aoeRadius: 50,
        element: 'ice',
        visual: 'targeted_aoe',
      },
    ],
  },

  corsair: {
    id: 'corsair',
    name: 'Corsair',
    role: 'Ranged Thrown',
    description: 'A rogue marksman armed with crossbow and blades. Explosive ordnance turns tight corridors into deathtraps.',
    hp: 100,
    stamina: 70,
    attackRange: 180,
    color: '#ff6b35',
    meshType: 'gunslinger',
    abilities: [
      {
        id: 'crossbow_bolt',
        name: 'Crossbow Bolt',
        slot: 'primary',
        cooldownTicks: 44,
        staminaCost: 0,
        range: 180,
        damage: 17,
        projectileSpeed: 7,
        aoeRadius: 0,
        element: 'none',
        visual: 'projectile',
      },
      {
        id: 'fan_of_knives',
        name: 'Fan of Knives',
        slot: 'q',
        cooldownTicks: 80,
        staminaCost: 18,
        range: 120,
        damage: 10,
        projectileSpeed: 6,
        aoeRadius: 0,
        element: 'none',
        visual: 'projectile',
        projectileCount: 3,
      },
      {
        id: 'explosive_bolt',
        name: 'Explosive Bolt',
        slot: 'e',
        cooldownTicks: 70,
        staminaCost: 20,
        range: 180,
        damage: 25,
        projectileSpeed: 6,
        aoeRadius: 50,
        element: 'fire',
        visual: 'projectile',
      },
      {
        id: 'barrel_bomb',
        name: 'Barrel Bomb',
        slot: 'r',
        cooldownTicks: 110,
        staminaCost: 22,
        range: 180,
        damage: 30,
        projectileSpeed: 0,
        aoeRadius: 60,
        element: 'fire',
        visual: 'targeted_aoe',
      },
    ],
  },

  pyromancer: {
    id: 'pyromancer',
    name: 'Pyromancer',
    role: 'Fire Mage',
    description: 'A conduit of infernal flame, scorching all who draw near. Even standing close invites immolation.',
    hp: 75,
    stamina: 110,
    attackRange: 180,
    color: '#ff6b35',
    meshType: 'fire_mage',
    abilities: [
      {
        id: 'fireball',
        name: 'Fireball',
        slot: 'primary',
        cooldownTicks: 48,
        staminaCost: 0,
        range: 180,
        damage: 20,
        projectileSpeed: 5,
        aoeRadius: 0,
        element: 'fire',
        visual: 'projectile',
      },
      {
        id: 'fire_nova',
        name: 'Fire Nova',
        slot: 'q',
        cooldownTicks: 80,
        staminaCost: 22,
        range: 0,
        damage: 28,
        projectileSpeed: 0,
        aoeRadius: 80,
        element: 'fire',
        visual: 'self_aoe',
      },
      {
        id: 'meteor',
        name: 'Meteor',
        slot: 'e',
        cooldownTicks: 120,
        staminaCost: 30,
        range: 180,
        damage: 45,
        projectileSpeed: 3,
        aoeRadius: 60,
        element: 'fire',
        visual: 'targeted_aoe',
      },
      {
        id: 'flame_shield',
        name: 'Flame Shield',
        slot: 'r',
        cooldownTicks: 140,
        staminaCost: 25,
        range: 0,
        damage: 8,
        projectileSpeed: 0,
        aoeRadius: 0,
        element: 'fire',
        visual: 'self_buff',
        duration: 80,
        buffEffect: 'reflect',
        buffValue: 8,
      },
    ],
  },

  void_weaver: {
    id: 'void_weaver',
    name: 'Void Weaver',
    role: 'Shadow Mage',
    description: 'A weaver of forbidden void energies. Drains life from the living and rends souls with corrupted ice.',
    hp: 80,
    stamina: 100,
    attackRange: 170,
    color: '#8b5cf6',
    meshType: 'void_mage',
    abilities: [
      {
        id: 'shadow_bolt',
        name: 'Shadow Bolt',
        slot: 'primary',
        cooldownTicks: 44,
        staminaCost: 0,
        range: 170,
        damage: 18,
        projectileSpeed: 6,
        aoeRadius: 0,
        element: 'shadow',
        visual: 'projectile',
      },
      {
        id: 'void_nova',
        name: 'Void Nova',
        slot: 'q',
        cooldownTicks: 80,
        staminaCost: 20,
        range: 0,
        damage: 25,
        projectileSpeed: 0,
        aoeRadius: 80,
        element: 'shadow',
        visual: 'self_aoe',
      },
      {
        id: 'ice_spike',
        name: 'Ice Spike',
        slot: 'e',
        cooldownTicks: 50,
        staminaCost: 16,
        range: 170,
        damage: 32,
        projectileSpeed: 7,
        aoeRadius: 0,
        element: 'ice',
        visual: 'projectile',
      },
      {
        id: 'life_drain',
        name: 'Life Drain',
        slot: 'r',
        cooldownTicks: 100,
        staminaCost: 22,
        range: 120,
        damage: 20,
        projectileSpeed: 4,
        aoeRadius: 0,
        element: 'shadow',
        visual: 'drain',
        healPercent: 0.5,
      },
    ],
  },
};
